name: test
on:
  push:
    branches:
    - '*'
env:
  CARGO_TERM_COLOR: always
jobs:

  test-macos-aarch64:
    runs-on: macOS-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
        targets: aarch64-apple-darwin
    - uses: actions/checkout@v3
    - run: cargo build --release --target=aarch64-apple-darwin --workspace --exclude frontend_sdl2

  test-web:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
        targets: wasm32-unknown-unknown
    - uses: actions/checkout@v3
    - run: cargo build --release --target=wasm32-unknown-unknown --manifest-path=web/Cargo.toml

  test-x86_64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]
    steps:
    - if: matrix.os == 'ubuntu-latest'
      name: 'Install dependencies (ubuntu)'
      run: |
        sudo apt update
        sudo apt install libudev-dev libasound2-dev libsdl2-dev libsdl2-ttf-dev
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v3
    - if: matrix.os == 'ubuntu-latest'
      run: cargo test --release --workspace
    - if: matrix.os != 'ubuntu-latest'
      run: cargo test --release --workspace --exclude frontend_sdl2
